# ============================================
# File: config.yaml
# ============================================
project_name: "churn-modeling"
version: "1.0.0"

data:
  raw_path: "data/raw/churn_modelling.csv"
  processed_train_path: "data/processed/train.parquet"
  processed_test_path: "data/processed/test.parquet"
  target_column: "Exited"
  test_size: 0.2
  random_state: 42
  initial_features: ['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
  numerical_vars: ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']
  categorical_vars: ['Geography', 'Gender', 'HasCrCard', 'IsActiveMember']
  
tuning:
  models_to_tune: ['LogisticRegression', 'RandomForest', 'XGBoost', 'SVC']
  cv_folds: 6
  optuna_trials_per_model: 5 # adjustable
  optimization_metric: 'f1'
  mlflow_experiment_name: "Churn_Model_Tuning_v1"
  all_best_params_output_path: "models/all_best_hyperparameters.json"

training:
  all_best_params_input_path: "models/all_best_hyperparameters.json"
  final_model_output_base_path: "models/final_churn_model" 
  mlflow_experiment_name: "Churn_Model_Training_v1"

evaluation:
  model_input_path: "models/final_churn_model.joblib"
  plots_output_dir: "reports/figures"
  shap_plots_output_dir: "reports/figures/shap"
  mlflow_experiment_name: "Churn_Model_Evaluation_v1"
  shap_kernel_background_samples: 100

api:
  title: "Churn Modeling"
  version: "1.0.0"
